services:
  label-studio:
    build: .
    restart: unless-stopped
    ports:
      - "8013:8013"
    environment:
      PRINTER_MODEL: QL-800
      PRINTER_PRINTER: file:///dev/usb/lp0
    devices:
      - /dev/usb/lp0:/dev/usb/lp0
    volumes:
      - ./data:/data
